Frontend fixes
lafranceinsoumise/agir.lafranceinsoumise.fr pull request #108
Opened 2020-12-08 15:34 UTC by giuseppedeponte

- Fix announcements
- Bigger desktop email input field on login form
- Personal setting link in app navigation
- Add is2022 prop to SupportGroupSerializer and EventSerializer
- LFI/NSP badge in event page group card

2020-12-08 17:17 UTC, aktiur requested changes

2020-12-08 17:17 UTC, aktiur commented on agir/api/context_processors.py
> +        "contact": "https://info.actionpopulaire.fr/contact/",
C'est `infos` au pluriel dans le nom de domaine

2020-12-08 17:22 UTC, giuseppedeponte commented on agir/api/context_processors.py
> +        "contact": "https://info.actionpopulaire.fr/contact/",
Bien vu !
Je corrige

2020-12-09 09:30 UTC, aktiur commented
Merge la PR gdp/frontend-fixes

2020-12-09 09:31 UTC, merged